import { ChapterQuizData } from "../quizTypes";

export const CH37_QUIZ: ChapterQuizData = {
  "chapterId": "ch37",
  "sectionQuizzes": {
    "37-1": [
      {
        "id": "q-37-1-1",
        "question": "What is 'AI-Assisted Coding'?",
        "options": [
          "The AI writing the entire app for you while you sleep",
          "Using AI tools (like GitHub Copilot or ChatGPT) to help write, debug, and document code",
          "Having an AI manager",
          "A robot that types on your keyboard"
        ],
        "correct": 1,
        "explanation": "AI-assisted coding enhances developer productivity by providing suggestions and automating boilerplate.",
        "difficulty": "easy"
      },
      {
        "id": "q-37-1-2",
        "question": "What is a potential risk of over-relying on AI for coding?",
        "options": [
          "The AI might get tired",
          "Loss of deep understanding, introduction of subtle bugs, and security vulnerabilities",
          "The code will be too fast for humans to read",
          "AI tools are too expensive for most companies"
        ],
        "correct": 1,
        "explanation": "Engineers must still verify and understand the code generated by AI to ensure quality and security.",
        "difficulty": "medium"
      },
      {
        "id": "q-37-1-3",
        "question": "How does AI-assisted coding change the role of a Junior Engineer?",
        "options": [
          "It makes the role obsolete",
          "It shifts the focus from syntax mastery to higher-level problem solving and verification",
          "It requires them to learn 10 more languages",
          "It doesn't change anything"
        ],
        "correct": 1,
        "explanation": "Juniors can move faster, but they must be more vigilant about learning the 'why' behind the code.",
        "difficulty": "medium"
      }
    ],
    "37-2": [
      {
        "id": "q-37-2-1",
        "question": "What is a 'Low-Code' platform?",
        "options": [
          "A platform that only uses low-level languages like C",
          "A development environment that uses visual interfaces and configuration instead of traditional hand-coding",
          "A platform for people with low IQ",
          "A platform that uses very little electricity"
        ],
        "correct": 1,
        "explanation": "Low-code and no-code platforms aim to democratize software development and speed up simple builds.",
        "difficulty": "easy"
      },
      {
        "id": "q-37-2-2",
        "question": "What is 'Citizen Development'?",
        "options": [
          "Building apps for the government",
          "Non-professional developers building business applications using low-code/no-code tools",
          "Building apps that only work in one city",
          "Hiring only citizens of a country to code"
        ],
        "correct": 1,
        "explanation": "Citizen development allows business users to solve their own problems without waiting for IT.",
        "difficulty": "medium"
      },
      {
        "id": "q-37-2-3",
        "question": "What is a major limitation of No-Code platforms for complex enterprise apps?",
        "options": [
          "They are too colorful",
          "Lack of flexibility, scalability issues, and difficulty with custom integrations",
          "They don't have a login screen",
          "They only work on Windows"
        ],
        "correct": 1,
        "explanation": "While great for simple apps, no-code often hits a 'wall' when highly custom or high-performance logic is needed.",
        "difficulty": "medium"
      }
    ],
    "37-3": [
      {
        "id": "q-37-3-1",
        "question": "What is WebAssembly (Wasm)?",
        "options": [
          "A new version of HTML",
          "A binary instruction format for a stack-based virtual machine, allowing near-native performance in web browsers",
          "A way to assemble hardware over the web",
          "A replacement for the entire internet"
        ],
        "correct": 1,
        "explanation": "Wasm allows languages like C++, Rust, and Go to run in the browser alongside JavaScript.",
        "difficulty": "medium"
      },
      {
        "id": "q-37-3-2",
        "question": "Which of these is a key benefit of WebAssembly?",
        "options": [
          "It's easier to read than JavaScript",
          "High performance for computationally intensive tasks (e.g., video editing, gaming, AI)",
          "It eliminates the need for CSS",
          "It makes websites smaller"
        ],
        "correct": 1,
        "explanation": "Wasm is designed for speed and efficiency, bringing desktop-class apps to the web.",
        "difficulty": "easy"
      },
      {
        "id": "q-37-3-3",
        "question": "Is WebAssembly intended to replace JavaScript?",
        "options": [
          "Yes, JavaScript is being deprecated",
          "No, it's designed to complement JavaScript, allowing them to work together",
          "Only for backend development",
          "Only for mobile apps"
        ],
        "correct": 1,
        "explanation": "Wasm and JS are designed to be used together, each handling what it does best.",
        "difficulty": "medium"
      }
    ],
    "37-4": [
      {
        "id": "q-37-4-1",
        "question": "What is 'Edge Computing'?",
        "options": [
          "Computing while standing on the edge of a cliff",
          "Distributed computing that brings computation and data storage closer to the location where it is needed (the 'edge' of the network)",
          "A very modern way of building computers",
          "Computing that only uses the edge of the hard drive"
        ],
        "correct": 1,
        "explanation": "Edge computing reduces latency and bandwidth usage by processing data locally (e.g., on IoT devices or CDN nodes).",
        "difficulty": "easy"
      },
      {
        "id": "q-37-4-2",
        "question": "What is a 'Cloud-Native' application?",
        "options": [
          "An application that was born in the cloud",
          "Applications designed specifically to take advantage of cloud computing models like microservices and containers",
          "An application that only works when it's raining",
          "An application that is owned by a cloud provider"
        ],
        "correct": 1,
        "explanation": "Cloud-native apps are built for scalability, resilience, and rapid change.",
        "difficulty": "medium"
      },
      {
        "id": "q-37-4-3",
        "question": "What is 'Serverless' computing (FaaS)?",
        "options": [
          "Computing without any computers",
          "A model where the cloud provider automatically manages the server infrastructure, and users only pay for the execution time",
          "Buying a server and then throwing it away",
          "A server that has no operating system"
        ],
        "correct": 1,
        "explanation": "Serverless allows developers to focus on code (functions) rather than server management.",
        "difficulty": "easy"
      }
    ],
    "37-5": [
      {
        "id": "q-37-5-1",
        "question": "What are the 'Skills of 2030' expected to emphasize for software engineers?",
        "options": [
          "Typing speed and memorizing APIs",
          "System architecture, AI orchestration, ethical judgment, and deep domain expertise",
          "Learning as many assembly languages as possible",
          "Working without any sleep"
        ],
        "correct": 1,
        "explanation": "As AI handles more 'low-level' coding, human engineers will focus on higher-level design and complex trade-offs.",
        "difficulty": "medium"
      },
      {
        "id": "q-37-5-2",
        "question": "What is 'Lifelong Learning' in software engineering?",
        "options": [
          "Going to school for 80 years",
          "The ongoing, voluntary, and self-motivated pursuit of knowledge due to the rapid pace of technological change",
          "Learning everything about one language and never changing",
          "A type of permanent certification"
        ],
        "correct": 1,
        "explanation": "In tech, your knowledge has a half-life; staying relevant requires constant learning.",
        "difficulty": "easy"
      },
      {
        "id": "q-37-5-3",
        "question": "What is 'Soft Skills' (or Durable Skills) for engineers?",
        "options": [
          "Being able to use soft keyboards",
          "Communication, empathy, teamwork, and leadership",
          "Writing code that is 'soft' and easy to change",
          "Skills that are only used in HR"
        ],
        "correct": 1,
        "explanation": "As coding becomes more automated, the human elements of collaboration become even more valuable.",
        "difficulty": "easy"
      }
    ],
    "37-6": [
      {
        "id": "q-37-6-1",
        "question": "What is 'Metaverse' development?",
        "options": [
          "Building the Facebook website",
          "Creating immersive, shared, 3D virtual spaces where users can interact in real-time",
          "A new type of database for metadata",
          "Writing code that writes code"
        ],
        "correct": 1,
        "explanation": "The metaverse involves technologies like VR, AR, and persistent world-building.",
        "difficulty": "medium"
      },
      {
        "id": "q-37-6-2",
        "question": "What is 'Spatial Computing'?",
        "options": [
          "Computing in outer space",
          "Human-computer interaction where the computer retains and manipulates referents to real objects and spaces",
          "Calculating the size of a room",
          "A type of 3D printing"
        ],
        "correct": 1,
        "explanation": "Spatial computing (like Apple Vision Pro) blends digital content with the physical world.",
        "difficulty": "medium"
      },
      {
        "id": "q-37-6-3",
        "question": "What is 'Digital Twin' technology?",
        "options": [
          "A backup of your hard drive",
          "A virtual representation of a physical object or system, used for simulation and monitoring",
          "Having two monitors",
          "A copy of an engineer's brain"
        ],
        "correct": 1,
        "explanation": "Digital twins are used in manufacturing, city planning, and healthcare to test scenarios safely.",
        "difficulty": "medium"
      }
    ],
    "37-7": [
      {
        "id": "q-37-7-1",
        "question": "What is 'Ambient Computing'?",
        "options": [
          "Computing with a lot of noise",
          "Computers that are integrated into our environment so they are available when needed but otherwise invisible",
          "A type of music for coders",
          "Computing in a very large room"
        ],
        "correct": 1,
        "explanation": "Think smart homes and wearable devices that work seamlessly without explicit commands.",
        "difficulty": "medium"
      },
      {
        "id": "q-37-7-2",
        "question": "What is 'Autonomous Software'?",
        "options": [
          "Software that drives a car",
          "Software that can self-heal, self-optimize, and self-configure without human intervention",
          "Software that is owned by nobody",
          "Software that doesn't need a license"
        ],
        "correct": 1,
        "explanation": "Autonomous systems use AI to manage their own lifecycle and operations.",
        "difficulty": "hard"
      },
      {
        "id": "q-37-7-3",
        "question": "What is 'Synthetic Data'?",
        "options": [
          "Data that is fake and useless",
          "Data that is artificially generated rather than produced by real-world events, used to train AI models privately and at scale",
          "Data that is made of plastic",
          "A type of music data"
        ],
        "correct": 1,
        "explanation": "Synthetic data helps overcome privacy concerns and data scarcity in AI training.",
        "difficulty": "medium"
      }
    ],
    "37-8": [
      {
        "id": "q-37-8-1",
        "question": "What is 'The Singularity' in tech-futurism?",
        "options": [
          "A single line of code that runs everything",
          "A hypothetical future point where technological growth becomes uncontrollable and irreversible, resulting in unfathomable changes to human civilization",
          "When a startup has only one founder",
          "The moment a computer is turned on for the first time"
        ],
        "correct": 1,
        "explanation": "The singularity is often associated with the emergence of Artificial General Intelligence (AGI).",
        "difficulty": "hard"
      },
      {
        "id": "q-37-8-2",
        "question": "What is 'AGI' (Artificial General Intelligence)?",
        "options": [
          "A very large AI",
          "AI that can understand, learn, and apply knowledge across a wide range of tasks at a human level",
          "AI that is good at playing games",
          "AI that can only do one thing very well"
        ],
        "correct": 1,
        "explanation": "AGI differs from current 'Narrow AI' which is specialized for specific tasks.",
        "difficulty": "medium"
      },
      {
        "id": "q-37-8-3",
        "question": "How should engineers prepare for a future with more AI?",
        "options": [
          "By fighting against it",
          "By embracing AI as a tool, focusing on high-level architecture, ethics, and human-centric design",
          "By changing careers immediately",
          "By ignoring it until it goes away"
        ],
        "correct": 1,
        "explanation": "Adaptability and a 'human-plus-AI' mindset are the best paths forward.",
        "difficulty": "easy"
      }
    ]
  },
  "examQuestions": [
    {
      "id": "exam-ch37-1",
      "question": "Which technology is most likely to bring desktop-class performance to web-based applications?",
      "options": ["HTML6", "WebAssembly", "jQuery", "Flash"],
      "correct": 1,
      "explanation": "WebAssembly allows near-native execution speed in the browser.",
      "difficulty": "easy"
    },
    {
      "id": "exam-ch37-2",
      "question": "What is the primary driver behind the 'Edge Computing' trend?",
      "options": [
        "Reducing latency and bandwidth for real-time applications",
        "Making the cloud more centralized",
        "Increasing the cost of servers",
        "Moving away from mobile devices"
      ],
      "correct": 0,
      "explanation": "Processing data closer to the source is essential for speed (e.g., self-driving cars, IoT).",
      "difficulty": "medium"
    },
    {
      "id": "exam-ch37-3",
      "question": "In a future where AI writes most of the code, what becomes the 'New Coding'?",
      "options": ["Typing faster", "Writing perfect prompts and high-level system specifications", "Fixing the AI's hardware", "Managing the AI's payroll"],
      "correct": 1,
      "explanation": "The engineer's role shifts toward intent, design, and verification.",
      "difficulty": "medium"
    },
    {
      "id": "exam-ch37-4",
      "question": "What is 'Prompt Injection'?",
      "options": [
        "A way to speed up an LLM",
        "A security vulnerability where an attacker provides a prompt that causes the AI to ignore its original instructions",
        "Adding more prompts to a queue",
        "A type of SQL injection"
      ],
      "correct": 1,
      "explanation": "Securing AI applications against malicious prompts is a new challenge for engineers.",
      "difficulty": "hard"
    },
    {
      "id": "exam-ch37-5",
      "question": "What is the 'No-Code' movement primarily about?",
      "options": [
        "Ending the career of software engineers",
        "Democratizing software creation so anyone can build apps without writing code",
        "A protest against complex code",
        "Writing code that doesn't use any semicolons"
      ],
      "correct": 1,
      "explanation": "No-code empowers business users and reduces the burden on IT for simple tasks.",
      "difficulty": "easy"
    },
    {
      "id": "exam-ch37-6",
      "question": "What is 'Human-in-the-Loop' (HITL)?",
      "options": [
        "A person stuck in a circular room",
        "A system that requires human intervention or approval at key decision points",
        "An AI that looks like a human",
        "A group of people standing in a circle"
      ],
      "correct": 1,
      "explanation": "HITL is crucial for safety and ethics in autonomous and AI-driven systems.",
      "difficulty": "medium"
    },
    {
      "id": "exam-ch37-7",
      "question": "Which of these is a likely 'New Role' in the engineering teams of 2030?",
      "options": ["Database Admin", "AI Ethicist / AI Orchestrator", "Webmaster", "COBOL Programmer"],
      "correct": 1,
      "explanation": "New roles will emerge focused on the safe and effective use of AI technologies.",
      "difficulty": "medium"
    },
    {
      "id": "exam-ch37-8",
      "question": "What is 'Open Source AI'?",
      "options": [
        "AI that is free to use",
        "AI where the weights, architecture, and training data are publicly available",
        "AI that only uses open-source libraries",
        "AI that writes open-source code"
      ],
      "correct": 1,
      "explanation": "Open-source AI (like Llama or Mistral) promotes transparency and decentralized innovation.",
      "difficulty": "medium"
    },
    {
      "id": "exam-ch37-9",
      "question": "What is 'Distributed AI'?",
      "options": [
        "AI that is given to everyone",
        "Training and running AI models across multiple devices or nodes rather than on one central server",
        "AI that is very good at distribution",
        "AI that works on different operating systems"
      ],
      "correct": 1,
      "explanation": "Distributed AI (and Federated Learning) improves privacy and utilizes edge resources.",
      "difficulty": "hard"
    },
    {
      "id": "exam-ch37-10",
      "question": "What is the most important mindset for an engineer facing the future?",
      "options": ["Fear of change", "Growth mindset and adaptability", "Fixed expertise", "Ignoring new tools"],
      "correct": 1,
      "explanation": "The ability to learn and adapt is the only constant in a rapidly changing field.",
      "difficulty": "easy"
    }
  ]
};
